export const HIPSTER_WORDS = [
  "artisanal", "kale", "chartreuse", "brooklyn", "brunch", "fingerstache",
  "kombucha", "vinyl", "polaroid", "ennui", "scenester", "thundercats",
  "raclette", "ramps", "salvia", "mlkshk", "letterpress", "narwhal",
  "schlitz", "tofu", "seitan", "kogi", "umami", "marfa", "wayfarers",
  "selvage", "shoreditch", "etsy", "occupy", "asymmetrical", "denim",
  "mustache", "beard", "flannel", "lumbersexual", "skateboard", "fixie",
  "single-origin", "coffee", "pour-over", "cold-brew", "espresso", "macchiato",
  "latte", "barista", "roast", "small-batch", "craft", "microbrewery", "ipa",
  "saison", "gose", "growler", "tap", "kegerator", "bespoke", "handcrafted",
  "heirloom", "locavore", "farm-to-table", "foraged", "fermented", "pickled",
  "cronut", "dumpster", "garage", "warehouse", "loft", "industrial", "exposed",
  "brick", "reclaimed", "salvaged", "upcycled", "thrift", "vintage", "retro",
  "throwback", "nostalgia", "analog", "lo-fi", "mixtape", "cassette",
  "synthwave", "vaporwave", "lomo", "polaroid", "instax", "filter", "moodboard",
  "aesthetic", "minimal", "scandi", "japandi", "wabi-sabi", "biophilic",
  "succulent", "macrame", "terrarium", "tattoo", "piercing", "intelligentsia",
  "pinterest", "tumblr", "viral", "trending", "stomping", "venmo", "uber",
  "lyft", "wifi", "podcast", "blog", "vlog", "newsletter", "substack",
  "patreon", "kickstarter", "etsy", "shoreditch", "echo", "park", "silver",
  "lake", "venice", "boutique", "concept", "store", "pop-up", "speakeasy",
  "rooftop", "garden", "communal", "table", "shared", "workspace", "wework",
  "freelance", "remote", "nomad", "digital", "detox", "wellness", "yoga",
  "meditation", "mindful", "cold-plunge", "sauna", "matcha", "chai", "turmeric",
  "ashwagandha", "ceremony", "ritual", "ritualistic", "ephemeral", "curated",
  "considered", "intentional", "slow", "fashion", "linen", "tencel", "merino",
  "alpaca", "cashmere", "deadstock", "indie", "boutique", "label", "lookbook",
  "zine", "ephemera", "broadsheet", "newsprint", "risograph", "letterpress",
  "typewriter", "fountain", "pen", "ink", "journal", "moleskine", "field",
  "notes", "bullet", "sketch", "doodle", "marginalia",
];
